site_name: Tinkerbell Docs
site_description: Designed for scalable provisioning of physical hardware, Tinkerbell is both open-source and cloud native. Contributed by Equinix Metal.
site_image: https://tinkerbell.org/images/social/tinkerbell-social-image.png

nav:
  - Home: index.md

  - Architecture: architecture.md

  - Services:
    - Boots: services/boots.md
    - Hegel: services/hegel.md
    - OSIE: services/osie.md
    - Tink: services/tink.md

  - Hardware Data: hardware-data.md
  - Templates: templates.md
  - Workflows: workflows.md

  - Setups:
    - Local Setup with Vagrant: setup/local-vagrant.md
    - Extending the Vagrant Setup: setup/extending-vagrant.md
    - Packet Setup with Terraform: setup/packet-terraform.md

  - Examples:
    - A Hello-world Workflow: examples/hello-world-workflow.md

  - Tink CLI Reference:
    - Hardware: cli-reference/hardware.md
    - Template: cli-reference/template.md
    - Workflow: cli-reference/workflow.md

  - Troubleshooting: troubleshooting.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  footer_logo: assets/packet.png
  font: false

extra_css:
  - stylesheets/extra.css
  - stylesheets/simple-grid.css
  - stylesheets/font-awesome.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tinkerbell
    - icon: fontawesome/brands/slack
      link: https://slack.packet.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tinkerbell_oss

plugins:
  - search
