site_name: Tinkerbell Docs
site_url: https://docs.tinkerbell.org
site_description: Designed for scalable provisioning of physical hardware, Tinkerbell is both open-source and cloud native. Contributed by Equinix Metal.
site_image: https://tinkerbell.org/images/social/tinkerbell-social-image.png
repo_url: https://github.com/tinkerbell/tinkerbell-docs

nav:
  - Home: index.md

  - Architecture: architecture.md

  - Services:
    - Boots: services/boots.md
    - Hegel: services/hegel.md
    - Image Registry: services/registry.md
    - OSIE: services/osie.md
    - Tink Server: services/tink-server.md
    - Tink Worker: services/tink-worker.md
    - Tink CLI: services/tink-cli.md

  - Workflows: 
    - Working with Workflows: workflows/working-with-workflows.md
    - A Hello-world Workflow: workflows/hello-world-workflow.md

  - Hardware Data: hardware-data.md
  - Templates: templates.md

  - Actions:
    - ActionHub: https://artifacthub.io/packages/search?kind=4
    - Action Architecture: actions/action-architecture.md
    - Creating a Basic Action: actions/creating-a-basic-action.md
  
  - Setting Up Tinkerbell:
    - Local Setup with Vagrant: setup/local-vagrant.md
    - Extending the Vagrant Setup: setup/extending-vagrant.md
    - Equinix Metal Setup with Terraform: setup/equinix-metal-terraform.md
    - Bare Metal or Equinix Metal with QEMU: setup/using-qemu.md
    - On bare metal with Docker: setup/on-bare-metal-with-docker.md

  - Deploying Operating Systems:
    - The Basics: deploying-operating-systems/the-basics.md
    - The Deployment: deploying-operating-systems/the-deployment.md
    - Example - Deploying Ubuntu: deploying-operating-systems/examples-ubuntu.md
    - Example - Deploying Ubuntu from Packer Machine Image: deploying-operating-systems/examples-ubuntu-packer.md
    - Example - Deploying Debian: deploying-operating-systems/examples-debian.md
    - Example - Deploying FreeBSD: deploying-operating-systems/examples-freebsd.md
    - Example - Deploying Red Hat Enterprise Linux and CentOS: deploying-operating-systems/examples-rhel-centos.md
    - Example - Deploying Windows: deploying-operating-systems/examples-win.md
    
  - Troubleshooting: troubleshooting.md

  - Contribute:
    - Welcome: contrib/index.md
    - Triage: contrib/triage.md
    - Contributing to Tink: contrib/tink.md

theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  footer_logo: assets/packet.png
  font: false

extra_css:
  - stylesheets/extra.css
  - stylesheets/simple-grid.css
  - stylesheets/font-awesome.min.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tinkerbell
    - icon: fontawesome/brands/slack
      link: https://slack.cncf.org/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/tinkerbell_oss

google_analytics:
  - UA-52258647-10
  - auto

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.superfences